// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BookExists(arg1) {
  return window['go']['main']['App']['BookExists'](arg1);
}

export function ListBooks() {
  return window['go']['main']['App']['ListBooks']();
}

export function ListEdgeVoices() {
  return window['go']['main']['App']['ListEdgeVoices']();
}

export function LoadProgress(arg1) {
  return window['go']['main']['App']['LoadProgress'](arg1);
}

export function LoadTtsSettings() {
  return window['go']['main']['App']['LoadTtsSettings']();
}

export function ReadBook(arg1) {
  return window['go']['main']['App']['ReadBook'](arg1);
}

export function SaveProgress(arg1, arg2) {
  return window['go']['main']['App']['SaveProgress'](arg1, arg2);
}

export function SaveTtsSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTtsSettings'](arg1, arg2, arg3, arg4);
}

export function Synthesize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Synthesize'](arg1, arg2, arg3);
}
