// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BookExists(arg1:string):Promise<boolean>;

export function ListBooks():Promise<Array<main.CategoryGroup>>;

export function ListEdgeVoices():Promise<Array<main.EdgeVoice>>;

export function LoadProgress(arg1:string):Promise<number>;

export function LoadTtsSettings():Promise<main.ttsSettings>;

export function ReadBook(arg1:string):Promise<string>;

export function SaveProgress(arg1:string,arg2:number):Promise<void>;

export function SaveTtsSettings(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Synthesize(arg1:string,arg2:string,arg3:string):Promise<Array<number>>;
